[package]
name = "bls_pubkey_calc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lambdaworks = "0.8"  # Specify the latest version of lambdaworks
hex = "0.4"         # For handling hex encoding
